### ISSUE TITLE
htmlTable should return an error if nrows=0

### ISSUE THREAD

**Issue by jkgrain** [gforge/htmlTable#11]
I was running a report that accidentally tried to pass a dataframe with zero rows to htmlTable().  That generated the following error:  Error in css.cell[row_nr, ] : subscript out of bounds.

I added error trapping to my code, but you should consider seq_along instead of for (nr in 1:nrow(x)).

thanks for a great package.

**Comment by gforge** [comment]
I prefer the shorter `1:nrow(x)` solution and I think the correct thing for the package to do one of the two:
- Throw an error since a zero-row input isn't printeable
- Return a string that contains a zero-row message

The error seems to be more in line with the general behaviour but I can see the frustration when accidentally knitting and everything crashes because of an unexpected zero-row result.

**Comment by raredd** [comment]
Since `cars[0, ]` isn't an error, could you have a simple check for 0 rows?

```
htmlTable(cars[0, ]) ## error
htmlTable(cars[0, ][NA, ]) ## no error
```

In the second the table structure (with no data) is printed as one might expect. The user can visually inspect the tables.

This would be similar to option 2

**Comment by lemna** [comment]
I'd prefer to have a warning at most, and an empty table (with caption, header, footer, etc.) if there are zero rows. This comes in handy when generating listings for clinical trials.
