### ISSUE TITLE
Enhancement Request - Create option to add CSS to header row

### ISSUE THREAD

**Issue by gowerc** [gforge/htmlTable#73]
Quite often we need to be able to add CSS to the column header row to either change the font size or add padding.  As far as I can tell there is no existing option to do this

**Comment by gforge** [comment]
Thanks for the suggestion, this has been available for a long time through the css.cell option. It is not entirely use-friendly as you need to provide a css.matrix with nrow(x) + 1 row so that the header css can be extracted.

I've take you suggestion and added more options to the new style-function that I'm about to release. It would be great if you could have a look at the branch feature/add_header_style and see that there are no unexpected bugs.

**Comment by gowerc** [comment]
Sure no problem,  which branch are the changes in ?

**Comment by gforge** [comment]
It's in the `feature/add_header_style` branch

**Comment by gforge** [comment]
I'm pushing the package to CRAN today, let know if you find something out of place

**Comment by gowerc** [comment]
Apologies work has been super busy and I haven't yet had a chance to test it. Feel free to push anyway and I will make a bug report if I find something later on.  Thank you for your work (I use this package a lot) !!
